package im.protoc.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * 数据库POJO
 * @author Misnearzhang
 *
 */
public class RequestPOJO implements Serializable{
		private Integer id;

		/**
		 *
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column offline_message.from
		 *
		 * @mbg.generated
		 */
		private Integer from;

		/**
		 *
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column offline_message.to
		 *
		 * @mbg.generated
		 */
		private Integer to;

		/**
		 *
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column offline_message.content
		 *
		 * @mbg.generated
		 */
		private String content;

		/**
		 *
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column offline_message.status
		 *
		 * @mbg.generated
		 */
		private String status;

		/**
		 *
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column offline_message.addTime
		 *
		 * @mbg.generated
		 */
		private Date addtime;

		/**
		 *
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column offline_message.updateTime
		 *
		 * @mbg.generated
		 */
		private Date updatetime;

	public Integer getId() {
		return id;
	}

	public RequestPOJO setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getFrom() {
		return from;
	}

	public RequestPOJO setFrom(Integer from) {
		this.from = from;
		return this;
	}

	public Integer getTo() {
		return to;
	}

	public RequestPOJO setTo(Integer to) {
		this.to = to;
		return this;
	}

	public String getContent() {
		return content;
	}

	public RequestPOJO setContent(String content) {
		this.content = content;
		return this;
	}

	public String getStatus() {
		return status;
	}

	public RequestPOJO setStatus(String status) {
		this.status = status;
		return this;
	}

	public Date getAddtime() {
		return addtime;
	}

	public RequestPOJO setAddtime(Date addtime) {
		this.addtime = addtime;
		return this;
	}

	public Date getUpdatetime() {
		return updatetime;
	}

	public RequestPOJO setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
		return this;
	}
}
